name = "umitone-lab-portfolio"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[pages_compatibility_flags]]
flag = "nodejs_compat"

[build]
command = "pnpm run build"

[env.production.vars]
NODE_ENV = "production"